apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: pingpongapp
  app.kubernetes.io/part-of: GitActionDemo
  app.kubernetes.io/managed-by: kustomize

images:
  - name: jayesh1604/pingpongapp
    newName: jayesh1604/pingpongapp
    newTag: latest
